# Fly.io configuration - Best free tier option!
app = "code-assistant"
primary_region = "ord"  # Chicago, change to nearest region

[build]
  dockerfile = "deployment/free-tier/Dockerfile.fly"

[env]
  PORT = "8080"
  PYTHON_VERSION = "3.11"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    interval = 10000
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"
    restart_limit = 0
    timeout = 2000
    tls_skip_verify = false

# Persistent volume for SQLite database
[mounts]
  source = "data"
  destination = "/data"

# Free tier: 3 shared-cpu-1x VMs with 256MB RAM each
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256