# Railway.app configuration for backend
[build]
builder = "DOCKERFILE"
dockerfilePath = "./deployment/free-tier/Dockerfile.railway"

[deploy]
startCommand = "uvicorn code_assistant.api:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "api"
port = 8000

[environments.production]
PYTHON_VERSION = "3.11"